export const regions: Record<string, string[]> = {
  NSW: [
    'Capital Region',
    'Central Coast',
    'Central West',
    'Coffs Harbour - Grafton',
    'Far West and Orana',
    'Hunter Valley exc Newcastle',
    'Illawarra',
    'Mid North Coast',
    'Murray',
    'New England and North West',
    'Newcastle and Lake Macquarie',
    'Richmond - Tweed',
    'Riverina',
    'Southern Highlands and Shoalhaven',
    'Sydney - Baulkham Hills and Hawkesbury',
    'Sydney - Blacktown',
    'Sydney - City and Inner South',
    'Sydney - Eastern Suburbs',
    'Sydney - Inner South West',
    'Sydney - Inner West',
    'Sydney - North Sydney and Hornsby',
    'Sydney - Northern Beaches',
    'Sydney - Outer South West',
    'Sydney - Outer West and Blue Mountains',
    'Sydney - Parramatta',
    'Sydney - Ryde',
    'Sydney - South West',
    'Sydney - Sutherland',
  ],
  ACT: ['Australian Capital Territory'],
  VIC: [
    'Ballarat',
    'Bendigo',
    'Geelong',
    'Hume',
    'Latrobe - Gippsland',
    'Melbourne - Inner',
    'Melbourne - Inner East',
    'Melbourne - Inner South',
    'Melbourne - North East',
    'Melbourne - North West',
    'Melbourne - Outer East',
    'Melbourne - South East',
    'Melbourne - West',
    'Mornington Peninsula',
    'North West',
    'Shepparton',
    'Warrnambool and South West',
  ],
  TAS: [
    'Hobart',
    'Launceston and North East',
    'South East',
    'West and North West',
  ],
  SA: [
    'Adelaide - Central and Hills',
    'Adelaide - North',
    'Adelaide - South',
    'Adelaide - West',
    'Barossa - Yorke - Mid North',
    'South Australia - Outback',
    'South Australia - South East',
  ],
  WA: [
    'Bunbury',
    'Mandurah',
    'Perth - Inner',
    'Perth - North East',
    'Perth - North West',
    'Perth - South East',
    'Perth - South West',
    'Western Australia - Wheat Belt',
    'Western Australia - Outback (North)',
    'Western Australia - Outback (South)',
  ],
  NT: ['Darwin', 'Northern Territory - Outback'],
  QLD: [
    'Brisbane - East',
    'Brisbane - North',
    'Brisbane - South',
    'Brisbane - West',
    'Brisbane Inner City',
    'Cairns',
    'Darling Downs - Maranoa',
    'Central Queensland',
    'Gold Coast',
    'Ipswich',
    'Logan - Beaudesert',
    'Mackay - Isaac - Whitsunday',
    'Moreton Bay - North',
    'Moreton Bay - South',
    'Queensland - Outback',
    'Sunshine Coast',
    'Toowoomba',
    'Townsville',
    'Wide Bay',
  ],
};

export default regions;
