/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type WhatsappChat = {
  _id: string;
  _type: 'whatsapp-chat';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  url?: string;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type ExternalResource = {
  _id: string;
  _type: 'external-resource';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  url?: string;
};

export type Group = {
  _id: string;
  _type: 'group';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | WhatsappChat
  | Slug
  | ExternalResource
  | Group
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: GROUPS_QUERY
// Query: *[_type == "group" && defined(slug.current)][0...12]{  _id, name, slug}
export type GROUPS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug;
}>;
// Variable: GROUP_QUERY
// Query: *[_type == "group" && slug.current == $slug][0]{  _id, name, slug}
export type GROUP_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
} | null;
// Variable: EXT_RESOURCES_QUERY
// Query: *[_type == "external-resource" && defined(slug.current)][0...12]{  _id, name, slug, url}
export type EXT_RESOURCES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug;
  url: string | null;
}>;
// Variable: EXT_RESOURCE_QUERY
// Query: *[_type == "external-resource" && slug.current == $slug][0]{  _id, name, slug, url}
export type EXT_RESOURCE_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  url: string | null;
} | null;
// Variable: W_CHATS_QUERY
// Query: *[_type == "whatsapp-chat" && defined(slug.current)][0...12]{  _id, name, slug}
export type W_CHATS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug;
}>;
// Variable: W_CHAT_QUERY
// Query: *[_type == "whatsapp-chat" && slug.current == $slug][0]{  _id, name, slug}
export type W_CHAT_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "group" && defined(slug.current)][0...12]{\n  _id, name, slug\n}': GROUPS_QUERYResult;
    '*[_type == "group" && slug.current == $slug][0]{\n  _id, name, slug\n}': GROUP_QUERYResult;
    '*[_type == "external-resource" && defined(slug.current)][0...12]{\n  _id, name, slug, url\n}': EXT_RESOURCES_QUERYResult;
    '*[_type == "external-resource" && slug.current == $slug][0]{\n  _id, name, slug, url\n}': EXT_RESOURCE_QUERYResult;
    '*[_type == "whatsapp-chat" && defined(slug.current)][0...12]{\n  _id, name, slug\n}': W_CHATS_QUERYResult;
    '*[_type == "whatsapp-chat" && slug.current == $slug][0]{\n  _id, name, slug\n}': W_CHAT_QUERYResult;
  }
}
