/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type RichTextSection = {
  _type: 'richTextSection';
  title?: string;
  content?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Video = {
  _type: 'video';
  videoLabel?: string;
  url?: string;
};

export type TextWithIllustration = {
  _type: 'textWithIllustration';
  heading?: string;
  tagline?: string;
  excerpt?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Gallery = {
  _type: 'gallery';
  images: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
};

export type Hero = {
  _type: 'hero';
  heading?: string;
  tagline?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Promotion = {
  _id: string;
  _type: 'promotion';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  link?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug: Slug;
  pageBuilder: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & Gallery)
    | ({
        _key: string;
      } & Video)
    | {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: 'promotion';
      }
  >;
  seo?: Seo;
};

export type Seo = {
  _type: 'seo';
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  noIndex?: boolean;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type DegrowthDefinition = {
  _id: string;
  _type: 'degrowth-definition';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  statement: string;
  quote: string;
  author: string;
  identifier?: string;
  citationText?: string;
  citationUrl?: string;
};

export type ExternalResource = {
  _id: string;
  _type: 'external-resource';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  url: string;
  image?: string;
};

export type GroupActivity = {
  _type: 'groupActivity';
  activityLabel: string;
  activityUrl?: string;
};

export type GroupLink = {
  _type: 'groupLink';
  label: string;
  category: 'facebook' | 'instagram' | 'mailing-list' | 'matrix' | 'substack';
  url: string;
};

export type Group = {
  _id: string;
  _type: 'group';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName: string;
  slug: Slug;
  shortName?: string;
  website?: string;
  blurb: string;
  groupPhoto?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText: string;
    caption?: string;
    attribution?: string;
    _type: 'image';
  };
  contactEmail?: string;
  links?: Array<
    {
      _key: string;
    } & GroupLink
  >;
  activities?: Array<
    {
      _key: string;
    } & GroupActivity
  >;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichTextSection
  | BlockContent
  | Video
  | TextWithIllustration
  | SanityImageCrop
  | SanityImageHotspot
  | Gallery
  | Hero
  | Promotion
  | Page
  | Seo
  | Slug
  | DegrowthDefinition
  | ExternalResource
  | GroupActivity
  | GroupLink
  | Group
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: GROUPS_QUERY
// Query: *[_type == "group" && defined(slug.current)][0...12]{  _id,   fullName,   slug,  shortName,   website,   blurb,  groupPhoto,  contactEmail,  links[],  activities[]}
export type GROUPS_QUERYResult = Array<{
  _id: string;
  fullName: string;
  slug: Slug;
  shortName: string | null;
  website: string | null;
  blurb: string;
  groupPhoto: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText: string;
    caption?: string;
    attribution?: string;
    _type: 'image';
  } | null;
  contactEmail: string | null;
  links: Array<
    {
      _key: string;
    } & GroupLink
  > | null;
  activities: Array<
    {
      _key: string;
    } & GroupActivity
  > | null;
}>;
// Variable: DEGROWTH_DEFINITIONS_QUERY
// Query: *[_type == "degrowth-definition"]{  _id,   statement,   quote,  author,   identifier,   citationText,  citationUrl,}
export type DEGROWTH_DEFINITIONS_QUERYResult = Array<{
  _id: string;
  statement: string;
  quote: string;
  author: string;
  identifier: string | null;
  citationText: string | null;
  citationUrl: string | null;
}>;
// Variable: EXT_RESOURCES_QUERY
// Query: *[_type == "external-resource"]{  _id,  title,  description,  url,  image,  logo}
export type EXT_RESOURCES_QUERYResult = Array<{
  _id: string;
  title: string;
  description: string;
  url: string;
  image: string | null;
  logo: null;
}>;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _type,   _createdAt,   _updatedAt,   _rev,  _id,   name,   slug,   title,  "seo": {    "title": coalesce(seo.title, title, ""),    "description": coalesce(seo.description,  ""),    "image": seo.image,    "noIndex": seo.noIndex == true  },  pageBuilder[]{    _key,    _type,    _type == "hero" => {      heading,      tagline,      image    },    _type == "video" => {      videoLabel,      url,    },    _type == "richTextSection" => {      title,      content,    },    _type == "gallery" => {      images[]{        _key,        ...,      },    },  }}
export type PAGE_QUERYResult = {
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  _id: string;
  name: null;
  slug: Slug;
  title: string | null;
  seo: {
    title: string | '';
    description: string | '';
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    noIndex: boolean | false;
  };
  pageBuilder: Array<
    | {
        _key: string;
        _type: 'gallery';
        images: Array<{
          _key: string;
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        }>;
      }
    | {
        _key: string;
        _type: 'hero';
        heading: string | null;
        tagline: string | null;
        image: {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        } | null;
      }
    | {
        _key: string;
        _type: 'reference';
      }
    | {
        _key: string;
        _type: 'richTextSection';
        title: string | null;
        content: BlockContent | null;
      }
    | {
        _key: string;
        _type: 'video';
        videoLabel: string | null;
        url: string | null;
      }
  >;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "group" && defined(slug.current)][0...12]{\n  _id, \n  fullName, \n  slug,\n  shortName, \n  website, \n  blurb,\n  groupPhoto,\n  contactEmail,\n  links[],\n  activities[]\n}': GROUPS_QUERYResult;
    '*[_type == "degrowth-definition"]{\n  _id, \n  statement, \n  quote,\n  author, \n  identifier, \n  citationText,\n  citationUrl,\n}': DEGROWTH_DEFINITIONS_QUERYResult;
    '*[_type == "external-resource"]{\n  _id,\n  title,\n  description,\n  url,\n  image,\n  logo\n}': EXT_RESOURCES_QUERYResult;
    '*[_type == "page" && slug.current == $slug][0]{\n  _type, \n  _createdAt, \n  _updatedAt, \n  _rev,\n  _id, \n  name, \n  slug, \n  title,\n  "seo": {\n    "title": coalesce(seo.title, title, ""),\n    "description": coalesce(seo.description,  ""),\n    "image": seo.image,\n    "noIndex": seo.noIndex == true\n  },\n  pageBuilder[]{\n    _key,\n    _type,\n    _type == "hero" => {\n      heading,\n      tagline,\n      image\n    },\n    _type == "video" => {\n      videoLabel,\n      url,\n    },\n    _type == "richTextSection" => {\n      title,\n      content,\n    },\n    _type == "gallery" => {\n      images[]{\n        _key,\n        ...,\n      },\n    },\n  }\n}': PAGE_QUERYResult;
  }
}
