import cn from '@/utils/cn';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const { body } = {
    body: cn([
      'bg-gray-050 dark:bg-gray-950 antialiased',
      'select-none',
      'focus-visible:outline-2 focus-visible:outline-black',
    ]),
  };

  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className="overscroll-none"
    >
      <body className={body}>{children}</body>
    </html>
  );
}
